-- this script to store the basic configuration for game program itself
-- and it is a little different from config.ini

config = {
	developers = {
		"Yanguam" ,
		"Fsu0413" ,
		"Fu Nima" ,
		"0147certainly" ,
		"忧郁の月兔" ,
		"lwtmusou",
	} ,

	kingdoms = { 
	"zhu", "hmx","yym","yyc","zhan","fsl","dld","xlc","slm","hzc","wai","touhougod" ,
	"wei", "shu", "wu", "qun", "god" 
	},
	kingdom_colors = {
		wei = "#547998",
		shu = "#D0796C",
		wu = "#4DB873",
		qun = "#8A807A",
		god = "#96943D",
		zhu ="#6b21b6",--"#CC00FF",
		hmx = "#cb0b0b",--"red",
		yym = "#2121b9",--"#547998",
		yyc = "#6b6b6b",--"#8A807A",
		zhan = "#21b621",--"Green",
		fsl = "#b68121",--"yellow",
		dld = "#b6216e",--"#D0796C",
		xlc = "#21b9b9",--"LightSeaGreen",
		slm = "#37a46b",--"#4DB873",
		hzc ="purple",
		wai = "#cf6c0b",--"orange",
		touhougod = "#96943D",
	},

	package_names = {
		--卡牌包
		"StandardCard",
		"StandardExCard",
		"Maneuvering",
		--"LingCards" ,
		--"New3v3Card",
		--"New3v3_2013Card",
		--"New1v1Card",
		--"Disaster" ,
		--"Joy" ,
		--"JoyEquip" ,
		--"YitianCard" ,
		"touhoucard",
		
		--武将包
		"protagonist",
		"th06",
		"th07",
		"th08",
		"th09",
		"th10",
		"th11",
		"th12",
		"th13",
		"th14",
		"th99",
		"thxwm",
		"thndj",
		"touhougod",
		"Standard", --此包内带pattern的定义 不能屏蔽。。。
		--"Wind",
		--"Fire",
		--"Thicket",
		--"Mountain",
		--"God",
		--"YJCM",
		--"YJCM2012",
		--"YJCM2013",
		--"Special3v3",
		--"Special1v1",
		--"Special1v1OL",
		--"Special1v1Ext" ,
		--"SP",
		--"Chaos",
		--"OL",
		--"BGM",
		--"BGMDIY",
		--"Hegemony",
		--"Formation",
		--"Power" ,--势包 屏蔽
		--"Ling",
		--"Ling2013" ,
		--"TigerFly" ,
		--"NostalStandard",
		--"NostalWind",
		--"NostalYJCM",
		--"NostalYJCM2012",
		--"NostalOther" ,
		--"Yitian",
		--"Wisdom",
		--"DC" ,
		"Test",	
	},

	surprising_generals = {
		"Rara" ,
		"Fsu0413" ,
		"lzxqqqq1" ,
		"lzxqqqq2" ,
		"funima" ,
		"jiaoshenmeanimei" ,
	},

	hulao_packages = {
		"standard",
		"wind"
	},

	xmode_packages = {
		"standard",
		"wind",
		"fire",
		"nostal_standard",
		"nostal_wind",
	},

	easy_text = {
		"太慢了，做两个俯卧撑吧！",
		"快点吧，我等的花儿都谢了！",
		"高，实在是高！",
		"好手段，可真不一般啊！",
		"哦，太菜了。水平有待提高。",
		"你会不会玩啊？！",
		"嘿，一般人，我不使这招。",
		"呵，好牌就是这么打地！",
		"杀！神挡杀神！佛挡杀佛！",
		"你也忒坏了吧？！"
	},

	robot_names = {
		"神社的赛钱箱",
		"魔法蘑菇",
		"洋馆的妖精女仆",
		"冻青蛙",
		"无法往生的幽灵" ,
		"白芋头麻薯",
		"居家用人偶",
		"妖怪兔",
		"寺子屋的小孩",
		"向日葵（严禁攀折践踏）",
		"棋艺超群的天狗",
		"河童重工普通职员",
		"地狱鸦",
		"火焰猫" ,
		"“UFO”",
		"吓人用妖怪伞",
		"寻宝用鼠",
		"非想天则",
		"修行不足的狸猫",
		"防腐僵尸",
		"付丧神（暂时）",
		"人间之里的普通人",
		"白泽球" ,
		"毛玉" ,
		"油库里" ,
		"罪袋" ,
	},

	roles_ban = {
		"kof_zhangliao",
		"kof_xuchu",
		"kof_zhenji",
		"kof_xiahouyuan",
		"kof_guanyu",
		"kof_machao",
		"kof_nos_huangyueying",
		"kof_huangzhong",
		"kof_jiangwei",
		"kof_menghuo",
		"kof_zhurong",
		"kof_sunshangxiang",
		"kof_nos_diaochan",
	},

	kof_ban = {
		"sunquan",
		"huatuo"
	},

	hulao_ban = {
		"yuji"
	},

	xmode_ban = {
		"huatuo",
		"zhangjiao",
		"caoren",
		"zhoutai",
		"yuji",
		"liubei",
		"diaochan",
		"huangyueying",
		"st_yuanshu",
		"st_huaxiong",
		"nos_zhangjiao",
		"nos_yuji",
	},

	basara_ban = {
		"dongzhuo",
		"zuoci",
		"shenzhugeliang",
		"shenlvbu",
		"bgm_lvmeng",
		"zhanggongqi"
	},

	hegemony_ban = {
		"xiahoujuan" ,
		"neo2013_sp_guanyu" ,
		"weiwudi" ,
	},

	pairs_ban = {
		"huatuo", "zhoutai", "zuoci", "bgm_pangtong", "shencaocao", "liaohua", "nos_zhoutai",
		"+luboyan",
		"simayi+zhenji", "simayi+dengai",
		"caoren+shenlvbu", "caoren+caozhi", "caoren+bgm_diaochan", "caoren+bgm_caoren", "caoren+neo_caoren", "caoren+nos_caoren",
		"nos_caoren+shenlvbu", "nos_caoren+caozhi", "nos_caoren+bgm_diaochan", "nos_caoren+bgm_caoren", "nos_caoren+neo_caoren",
		"guojia+dengai",
		"zhenji+zhangjiao", "zhenji+shensimayi", "zhenji+zhugejin", "zhenji+nos_zhangjiao", "zhenji+nos_wangyi",
		"zhanghe+yuanshu",
		"dianwei+weiyan",
		"dengai+zhangjiao", "dengai+shensimayi", "dengai+zhugejin", "dengai+nos_zhangjiao",
		"zhangfei+huanggai", "zhangfei+zhangchunhua", "zhangfei+nos_zhangchunhua",
		"zhugeliang+xushu", "zhugeliang+nos_xushu",
		"huangyueying+wolong", "huangyueying+ganning", "huangyueying+huanggai", "huangyueying+yuanshao", "huangyueying+yanliangwenchou",
		"huangzhong+xusheng",
		"wolong+luxun", "wolong+zhangchunhua", "wolong+nos_huangyueying", "wolong+nos_zhangchunhua",
		"sunquan+sunshangxiang",
		"ganning+nos_huangyueying",
		"lvmeng+yuanshu",
		"huanggai+sunshangxiang", "huanggai+yuanshao", "huanggai+yanliangwenchou", "huanggai+dongzhuo",
		    "huanggai+wuguotai", "huanggai+guanxingzhangbao", "huanggai+huaxiong", "huanggai+xiahouba",
		    "huanggai+nos_huangyueying", "huanggai+nos_guanxingzhangbao", "huanggai+neo_zhangfei",
		"luxun+yanliangwenchou", "luxun+guanxingzhangbao", "luxun+guanping", "luxun+heg_luxun",
		    "luxun+nos_liubei", "luxun+nos_yuji", "luxun+nos_guanxingzhangbao",
		"sunshangxiang+shensimayi", "sunshangxiang+heg_luxun",
		"sunce+guanxingzhangbao", "sunce+nos_guanxingzhangbao",
		"yuanshao+nos_huangyueying",
		"yanliangwenchou+zhangchunhua", "yanliangwenchou+nos_huangyueying", "yanliangwenchou+nos_zhangchunhua",
		"dongzhuo+shenzhaoyun", "dongzhuo+wangyi", "dongzhuo+diy_wangyuanji", "dongzhuo+nos_zhangchunhua", "dongzhuo+nos_wangyi",
		"shencaocao+caozhi",
		"shenlvbu+caozhi", "shenlvbu+liaohua", "shenlvbu+bgm_diaochan", "shenlvbu+bgm_caoren", "shenlvbu+neo_caoren",
		"shenzhaoyun+huaxiong",
		"caozhi+bgm_diaochan", "caozhi+bgm_caoren", "caozhi+neo_caoren",
		"gaoshun+zhangchunhua", "gaoshun+nos_zhangchunhua",
		"wuguotai+caochong",
		"zhangchunhua+guanxingzhangbao", "zhangchunhua+guanping", "zhangchunhua+xiahouba", "zhangchunhua+zhugeke",
		    "zhangchunhua+heg_luxun", "zhangchunhua+nos_liubei", "zhangchunhua+nos_yuji", "zhangchunhua+nos_guanxingzhangbao", "zhangchunhua+neo_zhangfei",
		"guanxingzhangbao+bgm_zhangfei", "guanxingzhangbao+nos_zhangchunhua",
		"liaohua+bgm_diaochan",
		"guanping+nos_zhangchunhua",
		"xiahouba+nos_zhangchunhua",
		"zhugeke+nos_zhangchunhua",
		"bgm_diaochan+bgm_caoren",
		"bgm_caoren+neo_caoren",
		"bgm_zhangfei+nos_guanxingzhangbao",
		"nos_liubei+nos_zhangchunhua",
		"nos_yuji+nos_zhangchunhua",
		"nos_zhangchunhua+heg_luxun", "nos_zhangchunhua+nos_guanxingzhangbao", "nos_zhangchunhua+neo_zhangfei",
		"caoren+dengshizai", "nos_caoren+dengshizai", "shenlvbu+dengshizai", "bgm_diaochan+dengshizai", "bgm_caoren+dengshizai", "neo_caoren+dengshizai",
		"jiangboyue+huangyueying", "jiangboyue+wolong", "jiangboyue+yuanshao",
		"jiangboyue+yanliangwenchou", "jiangboyue+ganning", "jiangboyue+luxun", "jiangboyue+zhanggongqi",
		"yt_caochong+caocao", "yuanshu+caocao",
		"lukang+nos_liubei", "lukang+wolong", "lukang+yuji", "jiangboyue+lukang", "lukang+yanliangwenchou", "lukang+guanxingzhangbao", "lukang+heg_luxun",
		"caoren+caizhaoji", "nos_caoren+caizhaoji", "bgm_caoren+caizhaoji", "neo_caoren+caizhaoji", "dengshizai+caizhaoji",
		"zhugejin+caizhaoji", "simayi+caizhaoji", "shensimayi+caizhaoji", "caozhi+caizhaoji", "shenlvbu+caizhaoji", "bgm_diaochan+caizhaoji",
		"wis_jiangwei+zhanggongqi", "luxun+zhanggongqi", "wis_jiangwei+xunyou", "kongrong+caozhi", "heg_dengai+guojia", "luji+erzhang", "luji+caozhi",
		"tadun+yuanshao", "tadun+shenlvbu", "zhuran+hetaihou", "liru+shenlvbu", "zhugejin+zhangjiao", "zhugejin+nos_zhangjiao"
	},

	couple_lord = "caocao",
	couple_couples = {
		"caopi|caozhi+zhenji",
		"simayi+zhangchunhua",
		"liubei|bgm_liubei+ganfuren|sp_sunshangxiang",
		"zhangfei|bgm_zhangfei+xiahoushi|xiahoujuan",
		"zhugeliang|wolong+huangyueying",
		"menghuo+zhurong",
		"zhouyu+xiaoqiao",
		"lvbu|dongzhuo+diaochan|bgm_diaochan",
		"sunjian+wuguotai",
		"sunce+daqiao|bgm_daqiao",
		"sunquan+bulianshi",
		"diy_simazhao+diy_wangyuanji",
		"liuxie|diy_liuxie+fuhuanghou"
	},

	convert_pairs = {
		"caiwenji->sp_caiwenji",
		"jiaxu->sp_jiaxu",
		"machao->sp_machao",
		"pangde->sp_pangde",
		"sunshangxiang->sp_sunshangxiang",
		"fuwan->neo_mushun" ,
	}
}
