name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04
    #strategy:
    #  matrix:
    #    os: [, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - uses: lukka/get-cmake@latest
      
      - name: install swig
        run: sudo apt install swig

      - name: Run CMake+Ninja without triplet
        uses: lukka/run-cmake@v3
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildDirectory: '${{ runner.workspace }}/build'

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: install swig
        run: |
          New-Item -Path "." -Name "tools" -ItemType "directory";
          (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.1.zip","tools/swigwin-4.0.1.zip");
          Expand-Archive .\tools\swigwin-4.0.1.zip .\tools;
          Move-Item -Path ".\tools\swigwin-4.0.1" -Destination ".\tools\swig"
          .\tools\swig\swig.exe --help
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - uses: lukka/get-cmake@latest

      - name: Run CMake+Ninja without triplet
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: '${{ runner.workspace }}/build'
          configure-options: "-G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH:STRING=%{QT5_DIR}"
